config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  constraints(subdomain: [ "", "www" ]) do
    root to: "marketing#index"
    get "/pricing", to: "marketing#pricing"
    get "/faq", to: "marketing#faq"
  end

  constraints subdomain: "app" do
    get "signin", to: "sessions#new"
    post "signin", to: "sessions#create"
    delete "signout", to: "sessions#destroy"

    get "signup", to: "users#new"
    post "signup", to: "users#create"

    get "checkout", to: "checkouts#new"
    
    resource :password_resets, only: %i[ new create edit update ]

    namespace :checkouts do
      post "webhooks", to: "webhooks#create"
    end

    patch "active_label", to: "active_labels#update"

    resources :trips do
      resources :days
      resources :transportations
      resources :activities
      resources :lodgings
      resources :sometimes, except: %i[ show edit destroy ]
      resources :summaries, module: "trips", only: [ :index ]
      resources :shares, module: "trips", only: [ :new ]
      resource :notes, module: "trips", only: [ :show ]
    end
    
    scope "/share", as: :share do
      resources :trips, only: :show, param: :token do
        resources :days, :transportations, :lodgings, :sometimes, :summaries, only: %i[ index show ]
      end
    end
    
    # Defines the root path route ("/")
    get "/", to: "trips#index"
  end

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#server_error"
  get "/422", to: "errors#unprocessable"
end

app/models/transportation.rb
class Transportation < ApplicationRecord
  include Happeningable

  enum :mode, %i[ plane car train ]
  
  FORM_PARAMS = [ :mode, :origin, :destination, :arrival ]
end

app/controllers/transportations_controller.rb
class TransportationsController < HappeningablesController 
  private
  
  def index_happeningables
    @trip.transportations
  end
  
  def new_happeningable
    Transportation.new happeningable_params
  end
  
  def happeningable_params
    form_params.extract! *Transportation::FORM_PARAMS
  end
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/views/transportations/_transportation.html.erb
<%= turbo_frame_tag "edit_#{dom_id happening}", class: "block" do %>
  <% if day_by_day %>
  	<div class="flex py-1">
  		<div class="w-1/4 sm:w-1/6 text-xs sm:text-sm">
  			<p class="font-medium"><%= human_time(happening.time) %></p> <p class="font-light">to</p>
  			<p class="font-medium"><%= human_time(happening.transportation.arrival) %></p>
  		</div>
  		<div class="w-full">
  			<div class="inline-flex items-center">
  				<%= icon_for(happening.transportation.mode, size: "10") %>
  				<p class="ml-3 sm:text-lg font-medium align-middle"><%= happening.transportation.origin%> to <%= happening.transportation.destination%></p>
  			</div>
  			<div class="mt-4 text-xs sm:text-sm text-slate-600">
  		    <%= 
  				auto_link(happening.notes, html: { class: "text-blue-500 underline", target: '_blank' }) do |text|
  					truncate(text, length: 35, omission: '...')
  				end 
  				%>
  			</div>
  		</div>

  		<div class="self-end w-1/12">
  			<%= render "shared/actions_menu", type: :transportation, item: happening, day: happening.day %>
  		</div>
  	</div>
  <% else %>
  	<div class="flex bg-slate-100 rounded px-4 py-1 mt-4">
  		<div class="grow sm:contents">
  			<div class="mr-2 sm:mr-8">
  				<div class="inline-flex items-center">
  					<%= icon_for(happening.transportation.mode, size: "12") %>
  					<p class="ml-3 text-base sm:text-lg font-medium align-middle"><%= happening.transportation.origin%> to <%= happening.transportation.destination%></p>
  				</div>

  			  <div class="flex items-center gap-2 my-2">
  					<%= image_tag "time.svg", class: "h-4 w-auto inline"%>
  			    <%= human_time(happening.time) %> to
  					<%= human_time(happening.transportation.arrival) %>
  				</div>

  			  <div class="flex items-center gap-2 my-2">
  					<%= image_tag "date.svg", class: "h-4 w-auto inline"%>
  			    <%= happening&.date&.strftime("%a, %b. %d") %>
  				</div>
  		  </div>

  		  <div class="mt-4 text-xs sm:text-sm text-slate-600 grow">
  		    <%= 
  				auto_link(happening.notes, html: { class: "text-blue-500 underline", target: '_blank' }) do |text|
  					truncate(text, length: 35, omission: '...')
  				end 
  				%>
  			</div>
  		</div>

  		<%= render "shared/actions_menu", type: :transportation, item: happening %>
  	</div>
  <% end %>
<% end %>

app/views/transportations/edit.html.erb
<%= turbo_frame_tag "edit_#{dom_id @happening}", class: "contents" do %>
  <%= form_with model: @happening, url: trip_transportation_path(trip: @trip, day: @day), data: { controller: "edit-day", turbo: "false" }, class: "contents" do |form| %>
  	<div class="flex flex-col sm:flex-row py-1">
  		<div class="mr-2">
  			<%= form.select :date, options_for_select(@happening.trip.days.map { |day| [day.date.strftime("%a, %b. %d"), day.date] }, @happening.date), {}, class: "ml-1 text-sm block rounded border-none outline outline-1 outline-gray-300" %>
			
  			<p class="text-xs sm:text-sm italic w-1/4 sm:w-1/6 mt-2 sm:mt-0">
  				<%= form.time_field :time, value: @happening.read_attribute(:time), class: "w-28 border-none rounded text-sm", required: true %>
  				<p class="font-light ml-10">to</p>
  				<%= form.time_field :arrival, value: @happening.transportation.arrival, class: "w-28 border-none rounded text-sm", required: true %>
  			</p>
		    
  		</div>

  		<div class="w-full">
  			<%= form.select :mode, options_for_select(Transportation.modes.keys, @happening.transportation.mode), {}, class: "border-none focus:ring-0 outline outline-1 outline-gray-300 rounded" %>
	
  			<div class="inline-flex items-center align-middle">
  				<p class="sm:ml-3 sm:text-lg font-medium align-middle">
  					<%= form.text_field :origin, value: @happening.transportation.origin, placeholder: "location", autofocus: true, required: true, data: { action: "focus->edit-day#setCursor" }, class: "w-20 border-none focus:ring-0 p-0" %>
  					to
  					<%= form.text_field :destination, value: @happening.transportation.destination, placeholder: "location", required: true, class: "max-w-32 mt-4 sm:mt-0 ml-4 sm:ml-16 border-none focus:ring-0 p-0" %>
  				</p>
  			</div>
	
  			<div class="mt-4 text-xs sm:text-sm">
  				<%= form.text_area :notes, placeholder: "e.g. arrival time, reservation details, things to bring, how early to leave", class: "w-full sm:w-4/5 border-0 focus:ring-0 outline outline-1 outline-gray-300 rounded text-xs sm:text-sm" %>
  			</div>
	
  			<%= form.submit "Save changes", class: "p-2 text-white text-sm bg-green-600 rounded-full mt-2 sm:mt-0 sm:float-right" %>
  		</div>
  	</div>
  <% end %>
<% end %>

app/views/transportations/index.html.erb
<div class="w-full">
	<div class="relative mb-8 sm:mb-12">
		<h1 class="font-bold text-2xl sm:text-4xl text-center">Transportation</h1>
		<%= link_to new_trip_transportation_path, class: "sm:absolute flex items-center justify-center max-w-20 mx-auto mt-2 top-0 right-0 sm:mr-4 bg-green-600 text-white px-3 py-2 rounded", "data-admin": "true" do %>
			<%= image_tag "plus.svg", class: "h-3 sm:h-5 w-auto mr-1" %>
			<p class="font-light text-xs sm:text-sm">New</p>
		<% end %>
	</div>
	
	<% if @happenings.any? %>
		<div class="px-4 lg:px-40">
	  	<%= render partial: "transportation", collection: @happenings, as: :happening, locals: { day_by_day: false } %>
		</div>
	<% else %>
		<p class="mx-auto max-w-sm px-4 font-medium text-gray-500">
			Nothing to show yet. Start by adding flights to and from home!
		</p>
	<% end %>
</div>

app/views/transportations/new.html.erb
<div class="mx-auto md:w-2/3 w-full mt-4 px-4">
  <h1 class="font-semibold text-3xl text-center">Add Transportation</h1>

  <%= form_with model: @happening, url: trip_transportations_path(trip: @trip, day: @day) do |form| %>
  	<div class="max-w-sm mx-auto">
  	  <div class="my-5">
  	    <%= form.label :date, class: "font-bold text-slate-700" %>
  	    <%= form.select :date, options_for_select(@trip.days.map { |day| [day.date.strftime("%a, %b. %d"), day.date] }, @day&.date), {}, class: "block rounded border-none outline outline-1 outline-gray-300" %>
  	  </div>

  	  <div class="my-5 flex justify-between">
  			<div>
  	    	<%= form.label "Departure", class: "font-bold text-slate-700" %>
  	    	<%= form.time_field :time, class: "block rounded border-none outline outline-1 outline-gray-300 w-36", required: true %>
  			</div>
			
  			<div>
  				<%= form.label "Arrival", class: "font-bold text-slate-700"%>
  				<%= form.time_field :arrival, class: "block rounded border-none outline outline-1 outline-gray-300 w-36", required: true %>
  			</div>
  		</div>
		
  	  <div class="my-5">
  	    <%= form.label "From", class: "font-bold text-slate-700" %>
  	    <%= form.text_field :origin, placeholder: "Enter a starting point", required: true, class: "block w-full border-none outline outline-1 outline-gray-300 rounded" %>
  	  </div>
	
  	  <div class="my-5">
  	    <%= form.label "To", class: "font-bold text-slate-700" %>
  	    <%= form.text_field :destination, placeholder: "Enter a destination", required: true, class: "block w-full border-none outline outline-1 outline-gray-300 rounded" %>
  	  </div>
	
  		<div class="my-5">
  	    <%= form.label "Travel mode", class: "font-bold text-slate-700" %>
  	    <%= form.select :mode, ["plane", "train", "car"], {}, class: "w-36 block rounded outline outline-1 outline-gray-300 border-none" %>
  		</div>
	
  	  <div class="my-5">
  	    <%= form.label :notes, class: "font-bold text-slate-700" %>
  	    <%= form.text_area :notes, rows: 5, placeholder: "e.g. duration, reservation details, things to bring, how early to leave", class: "block w-full border-none outline outline-1 outline-gray-300 rounded" %>
  	  </div>

  	  <div class="text-center">
  	  	<%= form.submit "Save this transportation", class: "text-center rounded-xl py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer" %>
  		</div>
  	<div>
  <% end %>
</div>