config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  constraints(subdomain: [ "", "www" ]) do
    root to: "marketing#index"
    get "/pricing", to: "marketing#pricing"
    get "/faq", to: "marketing#faq"
  end

  constraints subdomain: "app" do
    get "signin", to: "sessions#new"
    post "signin", to: "sessions#create"
    delete "signout", to: "sessions#destroy"

    get "signup", to: "users#new"
    post "signup", to: "users#create"

    get "checkout", to: "checkouts#new"
    
    resource :password_resets, only: %i[ new create edit update ]

    namespace :checkouts do
      post "webhooks", to: "webhooks#create"
    end

    patch "active_label", to: "active_labels#update"

    resources :trips do
      resources :days
      resources :transportations
      resources :activities
      resources :lodgings
      resources :sometimes, except: %i[ show edit destroy ]
      resources :summaries, module: "trips", only: [ :index ]
      resources :shares, module: "trips", only: [ :new ]
      resource :notes, module: "trips", only: [ :show ]
    end
    
    scope "/share", as: :share do
      resources :trips, only: :show, param: :token do
        resources :days, :transportations, :lodgings, :sometimes, :summaries, only: %i[ index show ]
      end
    end
    
    # Defines the root path route ("/")
    get "/", to: "trips#index"
  end

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#server_error"
  get "/422", to: "errors#unprocessable"
end

app/views/shared/_actions_menu.html.erb
<div class="self-end flex gap-1 ml-1 items-center min-w-8">
	<%= link_to edit_polymorphic_path([ :trip, type ], { trip: item.trip, id: item.id, day: local_assigns[:day] }), class: "font-semibold text-xs sm:text-sm text-slate-600", data: { admin: "true" } do %>
		<%= image_tag "pencil.svg", class: "h-3 sm:h-4 w-auto" %>
	<% end %>
	<%= button_to polymorphic_path([ :trip, type ], { trip: item.trip, id: item.id, day: local_assigns[:day] }), method: :delete, form: { data: { turbo_frame: "_top", turbo_confirm: "Are you sure you want to delete this #{type}?", admin: "true" } } do %>
		<%= image_tag "trash.svg", class: "h-3 sm:h-4 w-auto" %>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="relative flex items-center justify-center p-4 bg-amber-100 min-h-14" data-controller="navbar">
	<%= link_to "/", class: "absolute left-5" do %>
		<div class="flex items-center gap-2">
			<%= image_tag "logo.svg", class: "h-7 sm:h-10 w-auto"%>
			<span class="font-bold text-xl hidden lg:inline">RunwayHorse</span>
		</div>
	<% end %>
  
	
	<% if trip = Current.user&.active_trip || @trip %>
		<% if trip.days.present? %>
			<div name="mobile-trip-buttons" class="sm:hidden flex w-2/3 items-end justify-evenly font-semibold text-slate-600">
				<%= link_to trip_path(trip) do %>
					Home
				<% end %>
				<%= link_to trip_transportations_path(trip) do %>
					<%= image_tag "truck.svg", class: "w-6 h-auto"%>
				<% end %>
				<%= link_to trip_lodgings_path(trip) do %>
					<%= image_tag "home.svg", class: "w-6 h-auto"%>
				<% end %>
				<%= link_to trip_day_path(trip, trip.current_day) do %>
					<%= image_tag "calendar.svg", class: "w-6 h-auto"%>
				<% end %>
			</div>
			<div name="trip-buttons" class="hidden sm:flex w-1/2 justify-evenly font-semibold text-slate-600">
				<%= link_to trip_path(trip) do %>
					Home
				<% end %>
				<%= link_to "Transportation", trip_transportations_path(trip) %>
				<%= link_to "Lodging", trip_lodgings_path(trip) %>
				<%= link_to "Days", trip_day_path(trip, trip.current_day) %>
			</div>
		<% end %>
		
    <% if signed_in? %>
  		<div class="absolute right-1">
  			<div name="admin-land" class= "relative flex flex-col relative">
  				<button class="self-end flex items-center font-bold rounded-full text-gray-500" data-action="click->navbar#toggleDropdown">
  					<%= Current.user.initials %>
  					<%= image_tag "vertical_ellipses.svg", class: "h-5 w-auto" %>
  				</button>
  				<div class="hidden absolute top-6 right-1 z-50 flex flex-col justify-center items-center gap-2 w-44 py-2 rounded-lg shadow-xl bg-white text-sm text-gray-500 fade-in" data-navbar-target="dropdown">
  					<%= link_to "Buy a trip", checkout_path, class: "bg-green-600 rounded-full py-1 px-2 font-sembiold text-white", data: { turbo: false } %>
  					<div class="w-full text-center">
  						<%= link_to "All trips", root_path %>
  						<%= button_to "Sign out", signout_path, method: :delete, class: "pt-2 mt-2 text-red-600 border-t border-grey-500 font-semibold w-full" %>
  					</div>
  				</div>
  			</div>
  		</div>
    <% end %>
	<% end %>
</nav>