config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  constraints(subdomain: [ "", "www" ]) do
    root to: "marketing#index"
    get "/pricing", to: "marketing#pricing"
    get "/faq", to: "marketing#faq"
  end

  constraints subdomain: "app" do
    get "signin", to: "sessions#new"
    post "signin", to: "sessions#create"
    delete "signout", to: "sessions#destroy"

    get "signup", to: "users#new"
    post "signup", to: "users#create"

    get "checkout", to: "checkouts#new"
    
    resource :password_resets, only: %i[ new create edit update ]

    namespace :checkouts do
      post "webhooks", to: "webhooks#create"
    end

    patch "active_label", to: "active_labels#update"

    resources :trips do
      resources :days
      resources :transportations
      resources :activities
      resources :lodgings
      resources :sometimes, except: %i[ show edit destroy ]
      resources :summaries, module: "trips", only: [ :index ]
      resources :shares, module: "trips", only: [ :new ]
      resource :notes, module: "trips", only: [ :show ]
    end
    
    scope "/share", as: :share do
      resources :trips, only: :show, param: :token do
        resources :days, :transportations, :lodgings, :sometimes, :summaries, only: %i[ index show ]
      end
    end
    
    # Defines the root path route ("/")
    get "/", to: "trips#index"
  end

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#server_error"
  get "/422", to: "errors#unprocessable"
end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
  layout "marketing"
  skip_before_action :authenticate, :validate_access

  def index
  end

  def pricing
  end
  
  def faq
  end
end

app/views/marketing/_footer.html.erb
<footer class="flex flex-col min-h-28 bg-white p-4 justify-between text-center mt-20">
	<p class="font-bold mb-8">
		<%= mail_to "hello@runwayhorse.com", "Email me", class: "text-indigo-500" %>
		to get help on anything.
	</p>
	<p>
		Updates, info, and writing on the <%= link_to "blog", "https://world.hey.com/varun.kumar", class: "underline font-bold text-blue-500", target: "_blank" %>
		and on <%= link_to "X", "https://x.com/varunkumariam", class: "underline font-bold text-blue-500", target: "_blank" %>
	</p>

	<form
		novalidate
	  action="https://buttondown.email/api/emails/embed-subscribe/varunkumar"
	  method="post"
		target="_blank"
		onsubmit="this.submit(); window.location.reload()"
	>
	  <label for="bd-email" class="block italic text-gray-500 mt-3 mb-1">Subscribe to the blog and hear about other things I'm making:</label>
		
		<div class="w-[348px] mx-auto flex justify-between rounded-full border border-gray-500 py-1 pl-4 pr-1 mb-6">
	  	<input type="email" name="email" id="bd-email" class="grow text-slate-600 text-sm border-none focus:ring-0 focus:border-none" placeholder="Enter your email" />
  
	  	<button type="submit" value="Subscribe" class="bg-indigo-500 font-bold text-white text-sm py-1 px-3 rounded-full">
				Subscribe
			</button>
		</div>
	</form>
	<p class="text-slate-600 text-xs italic">RunwayHorse is built by <%= link_to "Varun Kumar", "https://varunkumar.com", target: "_blank", class: "text-xs underline text-blue-500" %>. Copyright @Varun Kumar. All rights reserved.</p>
</footer>

app/views/marketing/_navbar.html.erb
<nav class="relative flex flex-col sm:flex-row items-center justify-center p-4 bg-amber-50 min-h-24">
	<%= link_to root_path, class: "sm:absolute sm:left-5" do %>
		<div class="flex items-center gap-2">
			<%= image_tag "logo.svg", class: "h-7 sm:h-12 w-auto"%>
			<span class="font-bold text-xl sm:text-2xl inline">RunwayHorse</span>
		</div>
	<% end %>
	
	<div class="mt-4 sm:mt-0 sm:absolute sm:right-5">
		<%= link_to "FAQ", faq_path, class: "mr-4 font-medium text-indigo-600 text-sm sm:text-base" %>
		<%= link_to "Sign in", signin_url(subdomain: "app"), class: "mr-4 font-medium text-indigo-600 text-sm sm:text-base" %>
		<%= link_to "Use it for free", signup_url(subdomain: "app"), class: "bg-green-600 text-white text-xs sm:text-sm font-semibold p-2 rounded-full"%>
	</div>
</nav>

app/views/marketing/faq.html.erb
<div class="mx-auto max-w-xl min-h-[64vh]">
	<div>
		<h2 class="text-4xl font-extrabold bg-gradient-to-r from-amber-700 to-orange-400 text-transparent bg-clip-text text-center my-8">FAQ</h2>
		<section class="mb-4">
			<strong class="bg-gradient-to-r from-purple-200 to-pink-200 p-1 mr-1">Is there an app?</strong> There isn't a mobile app yet. You can still add RunwayHorse to your homescreen by following <a href="https://support.apple.com/guide/iphone/bookmark-favorite-webpages-iph42ab2f3a7/ios#iph4f9a47bbc" target="_blank" class="text-blue-500">these instructions for iPhone</a> or <a href="https://www.howtogeek.com/667938/how-to-add-a-website-to-your-android-home-screen/" target="_blank" class="text-blue-500">these for Android</a>.
		</section>
		
		<section class="mb-4">
			<strong class="bg-gradient-to-r from-purple-200 to-pink-200 p-1 mr-1">Can I plan multiple trips at once?</strong> Yes, you can plan as many trips at one time as you want. They're all available for you to see even after you're done with them.
		</section>
		
		<section class="mb-4">
			<strong class="bg-gradient-to-r from-purple-200 to-pink-200 p-1 mr-1">How does sharing work?</strong>In your trip home, copy the shareable link that fellow travelers can use without a RunwayHorse account. They'll be able to view, but not edit, everything on the trip.
		</section>
		
		<section class="mb-4">
			<strong class="bg-gradient-to-r from-purple-200 to-pink-200 p-1 mr-1">Is it safe to put my reservation numbers in?</strong>No one else, including us, can access your account. Everything you put into RunwayHorse is only for your eyes.
		</section>
	</div>
</div>

app/views/marketing/index.html.erb
<div class="flex flex-col justify-center gap-32 w-full">
	<div class="relative flex flex-col items-center justify-center h-[500px] sm:w-2/3 mx-auto">
		<div class="flex w-full justify-evenly mb-4 italic font-medium underline decoration-2 decoration-indigo-500">
			<p>"Exactly what I never knew I wanted"</p>
			<p class="hidden sm:block">"Really excited to have it on my trip"</p>
		</div>
		<h1 class="font-black text-4xl lg:text-7xl text-center bg-gradient-to-r from-amber-700 to-orange-400 text-transparent bg-clip-text min-h-fit py-1">Put together your travels effortlessly</h1>
		<h2 class="font-base text-xl lg:text-2xl text-center mt-8">RunwayHorse is the <strong>easy</strong> and <strong>beautiful</strong> way to <strong>organize your trip plans</strong> so that the Docs, Sheets, and Notes mess can finally be left behind</h2>
		<%= link_to "Use RunwayHorse for free", signup_url(subdomain: "app"), class: "p-4 text-xl lg:text-2xl rounded-full text-white font-bold mt-12 bg-green-600" %>
	</div>
	
	<div class="flex flex-col p-0 m-0">
		<section class="sm:w-2/3 sm:ml-20">
			<p class="text-3xl font-bold">
				No one telling you where to go, what to do, or where to stay.
			</p>
			<p class="mt-6 font-light text-xl">
				 Travel planning has an overwhelming amount of details. Gathered from a dozen different websites, these bits of information have no dedicated place to go.
			</p>
			<p class="mt-6 font-light text-xl">
				RunwayHorse is a home for the important things for your trip, things that were scattered in your inbox, in some note on your phone, or in a sheet always in need of formatting. Let us add the <strong class="font-bold">scaffolding to your planning</strong> so that you can <strong class="font-bold">focus on the details.</strong>
			</p>
			<p class="mt-6 font-light text-xl">
				See how <strong class="font-bold">simple</strong> and <strong class="font-bold">structured</strong> planning your trip can be:
			</p>
		</section>
		<%= video_tag "marketing/demo.mp4", poster: "marketing/home.png", plays_in_line: true, controls: "controls", class: "shadow-xl md:max-w-2xl lg:max-w-4xl xl:max-w-5xl h-auto sm:mx-auto mt-12" %>
	</div>
	
	<div class="flex flex-col">
		<section class="sm:w-2/3 sm:ml-20">
			<p class="text-4xl font-bold">
				The Transportation
			</p>
			<p class="mt-6 font-light text-xl">
				Put in all your flights, trains, and drives. See where you're going and how you're getting there.
			</p>
		</section>
		<%= image_tag "marketing/transportation.png", class: "shadow-xl max-w-sm md:max-w-2xl lg:max-w-4xl xl:max-w-5xl h-auto sm:mx-auto mt-12" %>
			
		<section class="sm:w-2/3 sm:ml-20 mt-20">
			<p class="text-4xl font-bold">
				The Lodging
			</p>
			<p class="mt-6 font-light text-xl">
				Keep track of your hotels and Airbnbs. Add check-in info, links, and addresses. Remember the details about where you're staying without clicking through a thousand links.
			</p>
		</section>
		<%= image_tag "marketing/lodging.png", class: "shadow-xl max-w-sm md:max-w-2xl lg:max-w-4xl xl:max-w-5xl h-auto sm:mx-auto mt-12" %>
		
		<section class="sm:w-2/3 sm:ml-20 mt-20">
			<p class="text-4xl font-bold">
				The Day-by-Day
			</p>
			<p class="mt-6 font-light text-xl">
				The daily plan. Add bookings, restaurants, activities, and notes. See your transportation, lodging, location, and tickets for each day.
			</p>
		</section>
		<%= image_tag "marketing/day_by_day.png", class: "shadow-xl max-w-sm md:max-w-2xl lg:max-w-4xl xl:max-w-5xl h-auto sm:mx-auto mt-12" %>
		<p class="mx-auto max-w-sm md:max-w-2xl lg:max-w-4xl xl:max-w-5xl mt-4 font-light text-lg">
			Have something you want to do sometime during the trip but you don't know when? Put it into Sometime and check it off when you get to it.
		</p>
		
		<section class="sm:w-2/3 sm:ml-20 mt-20">
			<p class="text-4xl font-bold">
				And More
			</p>
			<ul class="mt-6 list-image-[url(list_check.svg)] text-left mx-6 text-xl font-light space-y-4">
				<li>Share with anyone for viewing</li>
				<li>Add trip notes</li>
				<li>See the whole itinerary</li>
				<li>Open addresses in Google Maps</li>
				<li>Plan multiple trips at once</li>
			</ul>
		</section>
		
		
		<section class="mt-20 text-center">
			<%= link_to "Use RunwayHorse for free", signup_url(subdomain: "app"), class: "p-4 text-xl lg:text-2xl rounded-full text-white font-bold bg-green-600" %>
			<h2 class="text-slate-600 mt-4">RunwayHorse is completely free to use! Ditch your sheet or doc for your next trip</h2>
		</section>
	</div>
</div>


	

app/views/marketing/pricing.html.erb
<div class="mx-auto max-w-xl">
	<section>
		<h2 class="text-4xl font-extrabold bg-gradient-to-r from-amber-700 to-orange-400 text-transparent bg-clip-text text-center my-8">Pay per trip, not per month.</h2>
	
		<p class="">RunwayHorse isn't like other travel software. There's <strong>no monthly subscription</strong>, <strong>no associate "partners"</strong> selling you things, and <strong>no AI telling you how you should plan your trip</strong>.</p>
		<br>
		<p>Your buy a RunwayHorse Trip <strong>whenever you need it</strong>. Buying a trip gives you access to all the <strong>transportation, lodging, and day-by-day</strong> tools. You own that trip forever and can come back to it even after your travelling is done. You can even <strong>share a link</strong> that fellow travels can use without an account</p>
		<br>
		<p>When you're planning to set out again, buy another RunwayHorse Trip. <strong>Never pay for your travel tool while you're at home</strong>.</p>
	</section>
	<div class="border-2 border-gray-200 bg-orange-50 rounded-xl text-center max-w-sm mx-auto mt-12 text-slate-600">
		<p class="font-extrabold text-5xl text-indigo-700 bg-orange-50 my-4">$20<span class="text-sm font-normal"> a trip</span></p>
		
		<p class="text-left mx-20 font-medium mb-4 mt-1">Included:</p>
		<ul class="list-disc text-left mx-24">
			<li>Lodging keeper</li>
			<li>Transportation keeper</li>
			<li>Day-by-day</li>
			<li>Trip todos</li>
			<li>Trip summary</li>
			<li>Share for viewing</li>
			<li class="font-semibold">View your RunwayHorse itinerary as long as you want</li>
		</ul>
		
		<div class="p-4">
			<%= link_to "Try for free", signup_url(subdomain: "app"), class: "px-4 py-1 rounded-full bg-green-600 text-white font-semibold" %>
		</div>
	</div>
</div>