config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  constraints(subdomain: [ "", "www" ]) do
    root to: "marketing#index"
    get "/pricing", to: "marketing#pricing"
    get "/faq", to: "marketing#faq"
  end

  constraints subdomain: "app" do
    get "signin", to: "sessions#new"
    post "signin", to: "sessions#create"
    delete "signout", to: "sessions#destroy"

    get "signup", to: "users#new"
    post "signup", to: "users#create"

    get "checkout", to: "checkouts#new"
    
    resource :password_resets, only: %i[ new create edit update ]

    namespace :checkouts do
      post "webhooks", to: "webhooks#create"
    end

    patch "active_label", to: "active_labels#update"

    resources :trips do
      resources :days
      resources :transportations
      resources :activities
      resources :lodgings
      resources :sometimes, except: %i[ show edit destroy ]
      resources :summaries, module: "trips", only: [ :index ]
      resources :shares, module: "trips", only: [ :new ]
      resource :notes, module: "trips", only: [ :show ]
    end
    
    scope "/share", as: :share do
      resources :trips, only: :show, param: :token do
        resources :days, :transportations, :lodgings, :sometimes, :summaries, only: %i[ index show ]
      end
    end
    
    # Defines the root path route ("/")
    get "/", to: "trips#index"
  end

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#server_error"
  get "/422", to: "errors#unprocessable"
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :trip
  has_and_belongs_to_many :lodgings
  has_many :happenings, -> { order(time: :asc) }, dependent: :destroy

  def previous
    trip.days.find_by(date: date - 1)
  end

  def next
    trip.days.find_by(date: date + 1)
  end
  
  def night_lodging
    if lodgings.count == 1
      lodging = lodgings.first
      lodging unless lodging.end_date == date
    else
      lodgings.select { |lodging| lodging.start_date == date }.pop
    end
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_trip
  before_action :set_day
  
  allow_unauthenticated_access only: :show
  
  def show
  end

  def edit
  end

  def update
    @day.update!(day_params)

    redirect_to trip_day_path(@trip, @day)
  end

  private
  
  def set_trip
    @trip = Trip.find(params[:trip_id])
  end
  
  def set_day
    @day = Day.find(params[:id])
  end

  def day_params
    params.require(:day).permit(:homebase, :location, :notes)
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_day.html.erb
<div class="w-full justify-center relative" id="<%= dom_id day %>">
	<div id="day-header" class="mb-5">
		<div class="w-full inline-flex justify-center items-center gap-x-1 border-solid border-b-2 border-gray-300">
			<% if day.previous %>
				<%= link_to trip_day_path(day.trip, day.previous) do %>
					<%= image_tag "left_arrow.svg", class: "h-5 w-auto" %>
				<% end %>
			<% end %>
			
			<h3 class="font-medium text-lg sm:text-xl"><%= human_date(day.date, no_year: true)%></h3>
			<% if day.next %>
				<%= link_to trip_day_path(day.trip, day.next) do %>
					<%= image_tag "right_arrow.svg", class: "h-5 w-auto" %>
				<% end %>
			<% end %>
		</div>
		<div class="flex justify-evenly mt-3 gap-x-4">
			<%= render "lodging_header", trip: day.trip, lodging: day.night_lodging, day: day %>
			<%= render "location_header", trip: day.trip, location: day.location, day: day %>
		</div>
	</div>
  
	<% if day.happenings.any? %>
		<div class="divide-y">
			<% day.happenings.each do |happening| %>
				<%= render happening.happeningable, happening: happening, day_by_day: true %>
			<% end %>
		</div>
	<% else %>
		<p class="text-center text-sm text-gray-500 italic">
			Nothing planned for today
		</p>
	<% end %>
	
	<%= turbo_frame_tag "sometimes", src: trip_sometimes_path(day.trip) do %>
		<%= image_tag "spinner.gif", class: "h-6 w-auto mx-auto mt-8" %>
	<% end %>
</div>
	

app/views/days/_location_header.html.erb
<p class="flex flex items-center justify-center px-4 py-2 text-gray-500">
	<%= image_tag "map_pin.svg", class: "h-6 w-auto mr-1" %>
	<%= turbo_frame_tag "location" do %>
		<%= link_to edit_trip_day_path(trip, day), "admin-link": "true" do %>
			<% if location.present? %>
				<span>
					<%= location %>
				</span>
			<% else %>
				<span class="font-light">
					Add location
				</span>
			<% end %>
		<% end %>
	<% end %>
</p>

app/views/days/_lodging_header.html.erb
<div class="flex text-wrap justify-center items-start px-4 py-2 text-gray-500">
	<%= image_tag "home.svg", class: "h-6 w-auto mr-1" %>
		
	<% if lodging.present? %>
		<%= link_to edit_trip_lodging_path(trip, lodging, day: day) do %>
			<p class="max-w-40">
				<%= lodging.name %> 
				<%=
					auto_link(lodging.link, html: { class: "text-blue-500 underline", target: '_blank' }) do |text|
						truncate(text, length: 0, omission: '(link)')
					end
					%>
			</p>
		<% end %>
	<% else %>
		<%= link_to new_trip_lodging_path(trip, day: day), "admin-link": "true" do %>
			<span class="font-light">Add lodging</span>
		<% end %>
	<% end %>
</div>
	

app/views/days/edit.html.erb
<%= turbo_frame_tag "homebase" do %>
	<%= form_with(model: [ @trip, @day ], class: "contents", data: { controller: "edit-day", action: "focusout->edit-day#submit", turbo_frame: "_blank" }) do |form| %>
		<%= form.text_field :homebase, class: "rounded-md border border-gray-200 outline-none text-sm", autofocus: true %>
	<% end %>
<% end %>
	
<%= turbo_frame_tag "location" do %>
	<%= form_with(model: [ @trip, @day ], class: "contents", data: { controller: "edit-day", action: "focusout->edit-day#submit" }) do |form| %>
		<%= form.text_field :location, class: "rounded-md border border-gray-200 outline-none text-sm", autofocus: true %>
	<% end %>
<% end %>

app/views/days/show.html.erb
<div id="add-buttons" class="flex justify-end text-xs sm:text-sm flex gap-x-4 pr-2 mb-2 sm:mb-0" data-admin>
	<%= link_to new_trip_transportation_path(@day.trip, day: @day), class: "rounded p-2 bg-indigo-500 text-white flex items-center" do %>
		<%= image_tag "white_truck.svg", class: "mr-1 h-4 sm:h-6 w-auto" %>
		<p>Add transportation</p>
	<% end %>
	<%= link_to new_trip_activity_path(@day.trip, day: @day), class: "rounded p-2 bg-emerald-500 text-white flex items-center" do %>
		<%= image_tag "sparkles.svg", class: "mr-1 h-4 sm:h-6 w-auto" %>
		<p>Add activity</p>
	<% end %>
</div>

<div class="relative mx-auto w-full md:w-2/3 px-3 flex">
  <%= render @day %>
</div>